testsuite: Fix up two tests for recent libstdc++ header changes [PR101647]
After recent libstdc++ header changes <functional> no longer includes
(parts of?) <array> and doesn't have to and <memory> no longer includes
(parts of?) <initializer_list>.
This patch fixes:
testsuite/g++.dg/pr71389.C:10:39: error: aggregate 'std::array<std::array<int, 16>, 16> v13' has incomplete type and cannot be defined
as well as
testsuite/g++.dg/cpp0x/initlist48.C:11:6: error: 'initializer_list' in namespace 'std' does not name a template type; did you mean 'uninitialized_fill'?

2021-07-29  Jakub Jelinek  <jakub@redhat.com>

	PR testsuite/101647
	* g++.dg/pr71389.C: Include <array> instead of <functional>.
	* g++.dg/cpp0x/initlist48.C: Include also <initializer_list>.